[package]
name = "switcher"
version = "0.1.0"
authors = ["Erik St. Martin <alakriti@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gstreamer = { git = "https://github.com/sdroege/gstreamer-rs.git", branch = "master", features = ["v1_14"] }
#gstreamer = { version = "0.16.2", features = ["v1_14"] }
